version: "3.9"

services:
  inventory:
    build: .
    container_name: inventory-service
    ports:
      - "3000:3000"
    volumes:
      - ./cache:/app/cache
    command: ["node", "index.js", "-h", "0.0.0.0", "-p", "3000", "-c", 
"./cache"]

